language: bash
sudo: false
script:
  - bash ./script/build.sh
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ublamQnuGwVHurC2LAipTkKa6RF+PF3lYMXFMGJDNNZEiC9WohHCCgaBcLsjziWYd5JeZVSUohjf1ChfuFWVb+lZMQXTyOVbK1ILIQfx6tZCz19eGx4YQXNI8QwuElKiekop3Cghiy0FG4uXWJL0wVC4fUluEn26m7gHhfFkZmXXWDBML9tfn8YgkEtvtDlNHPi8FIIqNGN/83pJHElq9CatMX6LsAmJ2Aq5mFUpmQWL9bWzsgg4Qxzzl0YOuKuPL5ZT1SglAEyaFvQLswyN40rUHL2borHH+ALo+0j1uJWAmR1L8ykk4/ahqk5dmiLe4C6zW6x3vPUAWLrLkQYAOlUpUE6TKBjpp5jfzzAPSTmqQzl0dQCc+BdIL5EdIKa9OrbQ7jYuANNfzC+0D8rnmEhtkUsmE/hHYmhihwp0ujUQLp5oc/jgbpyeC6UOsOj+p6dDYJBfi0xpicVPony+s7RSf4Wk81UIZC6ksTx8TI7cw4M779fWZtfa7hA3LiuTtCg2Ri38ZhCJ9VJJRA+DVFbSY1z/Q49Y0IVfolvHe++gJJKMtyVu+SqyLmbxOkglfVm9n7sogEb+1EWLVkzC//7e+Dl4ZP8qmsk5c5ESnng2fFLE1s6NBIrN4Z1Z9nmHZp0d4Qi26s0FXvIrZ9bj3SJfmWOiKOt6z3eGiU92BlM=
