baseURL = "http://example.org/"
languageCode = "ja"
title = "m4kvn's blog"
theme = "dream"
copyright = "Copyright (c) 2018, m4kvn; all rights reserved."

[params]
  author = "m4kvn"
  description = "m4kvn simple blog"
  avatar = "https://avatars.githubusercontent.com/m4kvn"
  email = "fun.masahiro@gmail.com"
  github = "m4kvn"
  siteStartYear = 2018
  aboutHeader = "About"
